### ISSUE TITLE
typo in Readme

### ISSUE THREAD

**Issue by larsbo** [laravel-notification-channels/hipchat#12]
The service provider entry has a typo:

`NotificationChannels\HipChat\HipChatProvider::class,NotificationChannels\HipChat\HipChatProvider::class,`

should be

`NotificationChannels\HipChat\HipChatProvider::class,NotificationChannels\HipChat\HipChatServiceProvider::class,`

**Comment by pmatseykanets** [comment]
Good catch. Fixed. Thanks! 👍

**Comment by larsbo** [comment]
No problem :)

And I found another one: The room notification example has a wrong `new` keyword:

``` php
return new HipChatMessage::create()
            ->room('New Registrations')
            ->html("<strong>A new user has registered!</strong>")
            ->sucess()
            ->notify();
```

**Comment by pmatseykanets** [comment]
Thanks again! You're apparently good at this :)

**Comment by larsbo** [comment]
Thanks - maybe I should quit my job and do this full time ;-)
But I guess everybody else who is going to try the example code had found the errors, too :D
